/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_appLayout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as AppLayoutClubClubIdRouteImport } from './routes/_appLayout/_club.$clubId'
import { Route as AppLayoutClubClubIdMemberAuthRouteImport } from './routes/_appLayout/_club/$clubId/_memberAuth'
import { Route as AppLayoutClubClubIdAboutRouteImport } from './routes/_appLayout/_club/$clubId/about'
import { Route as AppLayoutClubClubIdMemberAuthIndexRouteImport } from './routes/_appLayout/_club/$clubId/_memberAuth/index'
import { Route as AppLayoutClubClubIdMemberAuthPostsIdRouteImport } from './routes/_appLayout/_club/$clubId/_memberAuth/posts.$id'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutClubClubIdRoute = AppLayoutClubClubIdRouteImport.update({
  id: '/_club/$clubId',
  path: '/$clubId',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutClubClubIdMemberAuthRoute =
  AppLayoutClubClubIdMemberAuthRouteImport.update({
    id: '/_memberAuth',
    getParentRoute: () => AppLayoutClubClubIdRoute,
  } as any)
const AppLayoutClubClubIdAboutRoute =
  AppLayoutClubClubIdAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AppLayoutClubClubIdRoute,
  } as any)
const AppLayoutClubClubIdMemberAuthIndexRoute =
  AppLayoutClubClubIdMemberAuthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLayoutClubClubIdMemberAuthRoute,
  } as any)
const AppLayoutClubClubIdMemberAuthPostsIdRoute =
  AppLayoutClubClubIdMemberAuthPostsIdRouteImport.update({
    id: '/posts/$id',
    path: '/posts/$id',
    getParentRoute: () => AppLayoutClubClubIdMemberAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/$clubId': typeof AppLayoutClubClubIdRouteWithChildren
  '/$clubId/about': typeof AppLayoutClubClubIdAboutRoute
  '/$clubId/': typeof AppLayoutClubClubIdMemberAuthIndexRoute
  '/$clubId/posts/$id': typeof AppLayoutClubClubIdMemberAuthPostsIdRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/': typeof AppLayoutIndexRoute
  '/$clubId': typeof AppLayoutClubClubIdMemberAuthIndexRoute
  '/$clubId/about': typeof AppLayoutClubClubIdAboutRoute
  '/$clubId/posts/$id': typeof AppLayoutClubClubIdMemberAuthPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/_appLayout/_club/$clubId': typeof AppLayoutClubClubIdRouteWithChildren
  '/_appLayout/_club/$clubId/_memberAuth': typeof AppLayoutClubClubIdMemberAuthRouteWithChildren
  '/_appLayout/_club/$clubId/about': typeof AppLayoutClubClubIdAboutRoute
  '/_appLayout/_club/$clubId/_memberAuth/': typeof AppLayoutClubClubIdMemberAuthIndexRoute
  '/_appLayout/_club/$clubId/_memberAuth/posts/$id': typeof AppLayoutClubClubIdMemberAuthPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/$clubId'
    | '/$clubId/about'
    | '/$clubId/'
    | '/$clubId/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/'
    | '/$clubId'
    | '/$clubId/about'
    | '/$clubId/posts/$id'
  id:
    | '__root__'
    | '/_appLayout'
    | '/signin'
    | '/signup'
    | '/_appLayout/'
    | '/_appLayout/_club/$clubId'
    | '/_appLayout/_club/$clubId/_memberAuth'
    | '/_appLayout/_club/$clubId/about'
    | '/_appLayout/_club/$clubId/_memberAuth/'
    | '/_appLayout/_club/$clubId/_memberAuth/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_club/$clubId': {
      id: '/_appLayout/_club/$clubId'
      path: '/$clubId'
      fullPath: '/$clubId'
      preLoaderRoute: typeof AppLayoutClubClubIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_club/$clubId/_memberAuth': {
      id: '/_appLayout/_club/$clubId/_memberAuth'
      path: ''
      fullPath: '/$clubId'
      preLoaderRoute: typeof AppLayoutClubClubIdMemberAuthRouteImport
      parentRoute: typeof AppLayoutClubClubIdRoute
    }
    '/_appLayout/_club/$clubId/about': {
      id: '/_appLayout/_club/$clubId/about'
      path: '/about'
      fullPath: '/$clubId/about'
      preLoaderRoute: typeof AppLayoutClubClubIdAboutRouteImport
      parentRoute: typeof AppLayoutClubClubIdRoute
    }
    '/_appLayout/_club/$clubId/_memberAuth/': {
      id: '/_appLayout/_club/$clubId/_memberAuth/'
      path: '/'
      fullPath: '/$clubId/'
      preLoaderRoute: typeof AppLayoutClubClubIdMemberAuthIndexRouteImport
      parentRoute: typeof AppLayoutClubClubIdMemberAuthRoute
    }
    '/_appLayout/_club/$clubId/_memberAuth/posts/$id': {
      id: '/_appLayout/_club/$clubId/_memberAuth/posts/$id'
      path: '/posts/$id'
      fullPath: '/$clubId/posts/$id'
      preLoaderRoute: typeof AppLayoutClubClubIdMemberAuthPostsIdRouteImport
      parentRoute: typeof AppLayoutClubClubIdMemberAuthRoute
    }
  }
}

interface AppLayoutClubClubIdMemberAuthRouteChildren {
  AppLayoutClubClubIdMemberAuthIndexRoute: typeof AppLayoutClubClubIdMemberAuthIndexRoute
  AppLayoutClubClubIdMemberAuthPostsIdRoute: typeof AppLayoutClubClubIdMemberAuthPostsIdRoute
}

const AppLayoutClubClubIdMemberAuthRouteChildren: AppLayoutClubClubIdMemberAuthRouteChildren =
  {
    AppLayoutClubClubIdMemberAuthIndexRoute:
      AppLayoutClubClubIdMemberAuthIndexRoute,
    AppLayoutClubClubIdMemberAuthPostsIdRoute:
      AppLayoutClubClubIdMemberAuthPostsIdRoute,
  }

const AppLayoutClubClubIdMemberAuthRouteWithChildren =
  AppLayoutClubClubIdMemberAuthRoute._addFileChildren(
    AppLayoutClubClubIdMemberAuthRouteChildren,
  )

interface AppLayoutClubClubIdRouteChildren {
  AppLayoutClubClubIdMemberAuthRoute: typeof AppLayoutClubClubIdMemberAuthRouteWithChildren
  AppLayoutClubClubIdAboutRoute: typeof AppLayoutClubClubIdAboutRoute
}

const AppLayoutClubClubIdRouteChildren: AppLayoutClubClubIdRouteChildren = {
  AppLayoutClubClubIdMemberAuthRoute:
    AppLayoutClubClubIdMemberAuthRouteWithChildren,
  AppLayoutClubClubIdAboutRoute: AppLayoutClubClubIdAboutRoute,
}

const AppLayoutClubClubIdRouteWithChildren =
  AppLayoutClubClubIdRoute._addFileChildren(AppLayoutClubClubIdRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutClubClubIdRoute: typeof AppLayoutClubClubIdRouteWithChildren
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutClubClubIdRoute: AppLayoutClubClubIdRouteWithChildren,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
