/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_appLayout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as AppLayoutClubRouteImport } from './routes/_appLayout/_club'
import { Route as AppLayoutClubClubIdIndexRouteImport } from './routes/_appLayout/_club/$clubId/index'
import { Route as AppLayoutClubClubIdAboutRouteImport } from './routes/_appLayout/_club/$clubId/about'
import { Route as AppLayoutClubClubIdPostsIdRouteImport } from './routes/_appLayout/_club/$clubId/posts.$id'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutClubRoute = AppLayoutClubRouteImport.update({
  id: '/_club',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutClubClubIdIndexRoute =
  AppLayoutClubClubIdIndexRouteImport.update({
    id: '/$clubId/',
    path: '/$clubId/',
    getParentRoute: () => AppLayoutClubRoute,
  } as any)
const AppLayoutClubClubIdAboutRoute =
  AppLayoutClubClubIdAboutRouteImport.update({
    id: '/$clubId/about',
    path: '/$clubId/about',
    getParentRoute: () => AppLayoutClubRoute,
  } as any)
const AppLayoutClubClubIdPostsIdRoute =
  AppLayoutClubClubIdPostsIdRouteImport.update({
    id: '/$clubId/posts/$id',
    path: '/$clubId/posts/$id',
    getParentRoute: () => AppLayoutClubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/$clubId/about': typeof AppLayoutClubClubIdAboutRoute
  '/$clubId/': typeof AppLayoutClubClubIdIndexRoute
  '/$clubId/posts/$id': typeof AppLayoutClubClubIdPostsIdRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/': typeof AppLayoutIndexRoute
  '/$clubId/about': typeof AppLayoutClubClubIdAboutRoute
  '/$clubId': typeof AppLayoutClubClubIdIndexRoute
  '/$clubId/posts/$id': typeof AppLayoutClubClubIdPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_appLayout/_club': typeof AppLayoutClubRouteWithChildren
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/_appLayout/_club/$clubId/about': typeof AppLayoutClubClubIdAboutRoute
  '/_appLayout/_club/$clubId/': typeof AppLayoutClubClubIdIndexRoute
  '/_appLayout/_club/$clubId/posts/$id': typeof AppLayoutClubClubIdPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/$clubId/about'
    | '/$clubId/'
    | '/$clubId/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/'
    | '/$clubId/about'
    | '/$clubId'
    | '/$clubId/posts/$id'
  id:
    | '__root__'
    | '/_appLayout'
    | '/signin'
    | '/signup'
    | '/_appLayout/_club'
    | '/_appLayout/'
    | '/_appLayout/_club/$clubId/about'
    | '/_appLayout/_club/$clubId/'
    | '/_appLayout/_club/$clubId/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_club': {
      id: '/_appLayout/_club'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutClubRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_appLayout/_club/$clubId/': {
      id: '/_appLayout/_club/$clubId/'
      path: '/$clubId'
      fullPath: '/$clubId/'
      preLoaderRoute: typeof AppLayoutClubClubIdIndexRouteImport
      parentRoute: typeof AppLayoutClubRoute
    }
    '/_appLayout/_club/$clubId/about': {
      id: '/_appLayout/_club/$clubId/about'
      path: '/$clubId/about'
      fullPath: '/$clubId/about'
      preLoaderRoute: typeof AppLayoutClubClubIdAboutRouteImport
      parentRoute: typeof AppLayoutClubRoute
    }
    '/_appLayout/_club/$clubId/posts/$id': {
      id: '/_appLayout/_club/$clubId/posts/$id'
      path: '/$clubId/posts/$id'
      fullPath: '/$clubId/posts/$id'
      preLoaderRoute: typeof AppLayoutClubClubIdPostsIdRouteImport
      parentRoute: typeof AppLayoutClubRoute
    }
  }
}

interface AppLayoutClubRouteChildren {
  AppLayoutClubClubIdAboutRoute: typeof AppLayoutClubClubIdAboutRoute
  AppLayoutClubClubIdIndexRoute: typeof AppLayoutClubClubIdIndexRoute
  AppLayoutClubClubIdPostsIdRoute: typeof AppLayoutClubClubIdPostsIdRoute
}

const AppLayoutClubRouteChildren: AppLayoutClubRouteChildren = {
  AppLayoutClubClubIdAboutRoute: AppLayoutClubClubIdAboutRoute,
  AppLayoutClubClubIdIndexRoute: AppLayoutClubClubIdIndexRoute,
  AppLayoutClubClubIdPostsIdRoute: AppLayoutClubClubIdPostsIdRoute,
}

const AppLayoutClubRouteWithChildren = AppLayoutClubRoute._addFileChildren(
  AppLayoutClubRouteChildren,
)

interface AppLayoutRouteChildren {
  AppLayoutClubRoute: typeof AppLayoutClubRouteWithChildren
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutClubRoute: AppLayoutClubRouteWithChildren,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
