/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClubRouteImport } from './routes/_authenticated/_club'
import { Route as AuthenticatedClubClubIdIndexRouteImport } from './routes/_authenticated/_club/$clubId/index'
import { Route as AuthenticatedClubClubIdAboutRouteImport } from './routes/_authenticated/_club/$clubId/about'
import { Route as AuthenticatedClubClubIdPostsIdRouteImport } from './routes/_authenticated/_club/$clubId/posts.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClubRoute = AuthenticatedClubRouteImport.update({
  id: '/_club',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClubClubIdIndexRoute =
  AuthenticatedClubClubIdIndexRouteImport.update({
    id: '/$clubId/',
    path: '/$clubId/',
    getParentRoute: () => AuthenticatedClubRoute,
  } as any)
const AuthenticatedClubClubIdAboutRoute =
  AuthenticatedClubClubIdAboutRouteImport.update({
    id: '/$clubId/about',
    path: '/$clubId/about',
    getParentRoute: () => AuthenticatedClubRoute,
  } as any)
const AuthenticatedClubClubIdPostsIdRoute =
  AuthenticatedClubClubIdPostsIdRouteImport.update({
    id: '/$clubId/posts/$id',
    path: '/$clubId/posts/$id',
    getParentRoute: () => AuthenticatedClubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/$clubId/about': typeof AuthenticatedClubClubIdAboutRoute
  '/$clubId/': typeof AuthenticatedClubClubIdIndexRoute
  '/$clubId/posts/$id': typeof AuthenticatedClubClubIdPostsIdRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/$clubId/about': typeof AuthenticatedClubClubIdAboutRoute
  '/$clubId': typeof AuthenticatedClubClubIdIndexRoute
  '/$clubId/posts/$id': typeof AuthenticatedClubClubIdPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_club': typeof AuthenticatedClubRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_club/$clubId/about': typeof AuthenticatedClubClubIdAboutRoute
  '/_authenticated/_club/$clubId/': typeof AuthenticatedClubClubIdIndexRoute
  '/_authenticated/_club/$clubId/posts/$id': typeof AuthenticatedClubClubIdPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/$clubId/about'
    | '/$clubId/'
    | '/$clubId/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/'
    | '/$clubId/about'
    | '/$clubId'
    | '/$clubId/posts/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/signin'
    | '/signup'
    | '/_authenticated/_club'
    | '/_authenticated/'
    | '/_authenticated/_club/$clubId/about'
    | '/_authenticated/_club/$clubId/'
    | '/_authenticated/_club/$clubId/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_club': {
      id: '/_authenticated/_club'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_club/$clubId/': {
      id: '/_authenticated/_club/$clubId/'
      path: '/$clubId'
      fullPath: '/$clubId/'
      preLoaderRoute: typeof AuthenticatedClubClubIdIndexRouteImport
      parentRoute: typeof AuthenticatedClubRoute
    }
    '/_authenticated/_club/$clubId/about': {
      id: '/_authenticated/_club/$clubId/about'
      path: '/$clubId/about'
      fullPath: '/$clubId/about'
      preLoaderRoute: typeof AuthenticatedClubClubIdAboutRouteImport
      parentRoute: typeof AuthenticatedClubRoute
    }
    '/_authenticated/_club/$clubId/posts/$id': {
      id: '/_authenticated/_club/$clubId/posts/$id'
      path: '/$clubId/posts/$id'
      fullPath: '/$clubId/posts/$id'
      preLoaderRoute: typeof AuthenticatedClubClubIdPostsIdRouteImport
      parentRoute: typeof AuthenticatedClubRoute
    }
  }
}

interface AuthenticatedClubRouteChildren {
  AuthenticatedClubClubIdAboutRoute: typeof AuthenticatedClubClubIdAboutRoute
  AuthenticatedClubClubIdIndexRoute: typeof AuthenticatedClubClubIdIndexRoute
  AuthenticatedClubClubIdPostsIdRoute: typeof AuthenticatedClubClubIdPostsIdRoute
}

const AuthenticatedClubRouteChildren: AuthenticatedClubRouteChildren = {
  AuthenticatedClubClubIdAboutRoute: AuthenticatedClubClubIdAboutRoute,
  AuthenticatedClubClubIdIndexRoute: AuthenticatedClubClubIdIndexRoute,
  AuthenticatedClubClubIdPostsIdRoute: AuthenticatedClubClubIdPostsIdRoute,
}

const AuthenticatedClubRouteWithChildren =
  AuthenticatedClubRoute._addFileChildren(AuthenticatedClubRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClubRoute: typeof AuthenticatedClubRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClubRoute: AuthenticatedClubRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
